version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/home/dockeruser/project
      - gems:/usr/local/bundle
    links:
      - redis

  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379

volumes:
  gems:
    external:
      name: gems
